### ISSUE TITLE
can not build mono project

### ISSUE THREAD

**Issue by haoxianhan** [yfakariya/msgpack-rpc-cli#2]
Even I change the msgpack-cli ref to 4.0 version, it seem not build successful.

the error : Error CS1061: 'MsgPack.Unpacker' does not contain a definition for 'TryRead' and no extension method 'TryRead' accepting a first argument of type 'MsgPack.Unpacker' could be found (are you missing a using directive or an assembly reference?) (CS1061) (MsgPack.Rpc.Mono)

And It also tips : Serialization not in MsgPack namespaces.

**Comment by yfakariya** [comment]
Sorry, I just forgot to update Mono solution. I've updated solution/projects, so would you check latest commits?

**Comment by haoxianhan** [comment]
Hey, It works after pull the latest commits.
More, does it use for Xamarin or Xamarin.Form possibly?

**Comment by yfakariya** [comment]
Sorry for the delay so much.
MsgPack-RPC CLI doesn't support Xamarin now. It might run if the everything are lucky. MsgPack.dll itselft can run on Xamarin Androind and Xamarin iOS with some limitation due to AOT and value type generics, but some Socket features might not be run as expected.
