### ISSUE TITLE
Example Request

### ISSUE THREAD

**Issue by Xylios13** [yfakariya/msgpack-rpc-cli#3]
Hello. Me and my colleague are trying to use your msgpack-rpc-cli implementation in C#, however we are having difficulties understanding how we can create a service that the server can provide to the client. 

We tried following your Quick Start instructions, but we are still having some difficulties.

So we would like to ask you if you can provide a simple example that we can run and test on Visual Studio. We believe if we have an example with a client and server interacting we can build our application from that.

Thank you for your time, best regards.

**Comment by NextSim** [comment]
I've been struggling to follow the quick start instructions as well.  I installed MsgPack.Cli v0.9.2 from NuGet, added the using statement for MsgPack, but there is no definition for RpcClientConfiguration in it.
